"""Seed real exam-quality questions for NDA, JEE, NEET banks."""
import json, uuid, random
from pathlib import Path

BANK_DIR = Path(__file__).parent.parent / "data" / "question_banks"

# ---------------------------------------------------------------------------
# NDA questions
# ---------------------------------------------------------------------------
NDA = [
  # --- Mathematics: Algebra ---
  {"subject":"Mathematics","topic":"Algebra","difficulty":1,"question_text":"If α and β are roots of x²−5x+6=0, find α²+β².","options":["13","25","11","7"],"correct_index":0,"explanation":"α+β=5, αβ=6. α²+β²=(α+β)²−2αβ=25−12=13."},
  {"subject":"Mathematics","topic":"Algebra","difficulty":2,"question_text":"How many 4-digit numbers can be formed using digits 1,2,3,4,5 without repetition?","options":["120","60","24","240"],"correct_index":0,"explanation":"⁵P₄=5×4×3×2=120."},
  {"subject":"Mathematics","topic":"Algebra","difficulty":2,"question_text":"Find ⁸C₃.","options":["56","28","70","84"],"correct_index":0,"explanation":"⁸C₃=8!/(3!5!)=(8×7×6)/6=56."},
  {"subject":"Mathematics","topic":"Algebra","difficulty":2,"question_text":"The coefficient of x³ in (1+x)⁸ is:","options":["56","28","8","70"],"correct_index":0,"explanation":"⁸C₃=56."},
  {"subject":"Mathematics","topic":"Algebra","difficulty":1,"question_text":"If log₂ 8=x, find x.","options":["3","2","4","8"],"correct_index":0,"explanation":"log₂ 2³=3."},
  {"subject":"Mathematics","topic":"Algebra","difficulty":2,"question_text":"In an AP, if sum of n terms is 3n²+5n, find the common difference.","options":["6","3","5","10"],"correct_index":0,"explanation":"aₙ=Sₙ−Sₙ₋₁=6n+2; d=aₙ₊₁−aₙ=6."},
  {"subject":"Mathematics","topic":"Algebra","difficulty":2,"question_text":"In a GP, 3rd term=4 and 6th term=32. Find the common ratio.","options":["2","4","8","√2"],"correct_index":0,"explanation":"ar²=4, ar⁵=32 → r³=8 → r=2."},
  {"subject":"Mathematics","topic":"Algebra","difficulty":1,"question_text":"The modulus of the complex number 3+4i is:","options":["5","7","3","4"],"correct_index":0,"explanation":"|3+4i|=√(9+16)=5."},
  {"subject":"Mathematics","topic":"Algebra","difficulty":2,"question_text":"n(A∪B)=60, n(A)=35, n(B)=40. Find n(A∩B).","options":["15","25","20","10"],"correct_index":0,"explanation":"n(A∩B)=35+40−60=15."},
  {"subject":"Mathematics","topic":"Algebra","difficulty":3,"question_text":"Number of arrangements of letters in 'MISSISSIPPI':","options":["34650","30240","11880","25200"],"correct_index":0,"explanation":"11!/(1!4!4!2!)=34650."},
  {"subject":"Mathematics","topic":"Algebra","difficulty":2,"question_text":"If 2ˣ⁺¹=32, find x.","options":["4","3","5","2"],"correct_index":0,"explanation":"2ˣ⁺¹=2⁵ ⟹ x+1=5 ⟹ x=4."},
  {"subject":"Mathematics","topic":"Algebra","difficulty":1,"question_text":"The number of subsets of a set with 4 elements is:","options":["16","8","12","4"],"correct_index":0,"explanation":"2⁴=16 subsets."},
  # --- Mathematics: Calculus ---
  {"subject":"Mathematics","topic":"Calculus","difficulty":1,"question_text":"d/dx [x³−3x²+5]=","options":["3x²−6x","3x²+6x","x³−6x","3x−6"],"correct_index":0,"explanation":"Power rule: 3x²−6x."},
  {"subject":"Mathematics","topic":"Calculus","difficulty":2,"question_text":"∫(2x+3)dx from 0 to 2 equals:","options":["10","8","14","12"],"correct_index":0,"explanation":"[x²+3x]₀²=(4+6)−0=10."},
  {"subject":"Mathematics","topic":"Calculus","difficulty":2,"question_text":"d/dx [sin(x²)]=","options":["2x cos(x²)","cos(x²)","2sinx cosx","−2x cos(x²)"],"correct_index":0,"explanation":"Chain rule: cos(x²)·2x=2x cos(x²)."},
  {"subject":"Mathematics","topic":"Calculus","difficulty":2,"question_text":"lim(x→0) sinx/x=","options":["1","0","∞","Undefined"],"correct_index":0,"explanation":"Standard limit: lim(x→0) sinx/x=1."},
  {"subject":"Mathematics","topic":"Calculus","difficulty":3,"question_text":"Area bounded by y=x² and y=x is:","options":["1/6","1/3","1/2","1/4"],"correct_index":0,"explanation":"∫₀¹(x−x²)dx=[x²/2−x³/3]₀¹=1/2−1/3=1/6."},
  {"subject":"Mathematics","topic":"Calculus","difficulty":2,"question_text":"d/dx [e^(3x)]=","options":["3e^(3x)","e^(3x)","3xe^(3x)","eˣ"],"correct_index":0,"explanation":"Chain rule: e^(3x)·3=3e^(3x)."},
  {"subject":"Mathematics","topic":"Calculus","difficulty":3,"question_text":"∫₀^(π/2) sin²x dx=","options":["π/4","π/2","1","π/8"],"correct_index":0,"explanation":"Using sin²x=(1−cos2x)/2: [x/2−sin2x/4]₀^(π/2)=π/4."},
  {"subject":"Mathematics","topic":"Calculus","difficulty":2,"question_text":"f(x)=x³−3x has a local minimum at x=","options":["1","−1","0","3"],"correct_index":0,"explanation":"f'(x)=3x²−3=0 → x=±1. f''(1)=6>0 → minimum at x=1."},
  {"subject":"Mathematics","topic":"Calculus","difficulty":2,"question_text":"∫ x·eˣ dx=","options":["eˣ(x−1)+C","xeˣ+C","eˣ+C","eˣ(x+1)+C"],"correct_index":0,"explanation":"By parts: xeˣ−eˣ+C=eˣ(x−1)+C."},
  {"subject":"Mathematics","topic":"Calculus","difficulty":1,"question_text":"Slope of tangent to y=x² at x=3 is:","options":["6","9","3","12"],"correct_index":0,"explanation":"dy/dx=2x; at x=3: slope=6."},
  {"subject":"Mathematics","topic":"Calculus","difficulty":1,"question_text":"∫ sin x dx=","options":["−cos x+C","cos x+C","sin x+C","−sin x+C"],"correct_index":0,"explanation":"∫sinx dx=−cosx+C."},
  # --- Mathematics: Trigonometry ---
  {"subject":"Mathematics","topic":"Trigonometry","difficulty":1,"question_text":"sin30°+cos60° =","options":["1","√3/2","1/2","√2"],"correct_index":0,"explanation":"1/2+1/2=1."},
  {"subject":"Mathematics","topic":"Trigonometry","difficulty":1,"question_text":"The principal value of sin⁻¹(−1/2) is:","options":["−π/6","π/6","−π/3","5π/6"],"correct_index":0,"explanation":"Principal value in [−π/2,π/2]: −π/6."},
  {"subject":"Mathematics","topic":"Trigonometry","difficulty":2,"question_text":"Maximum value of 3sinθ+4cosθ is:","options":["5","7","4","3"],"correct_index":0,"explanation":"√(a²+b²)=√(9+16)=5."},
  {"subject":"Mathematics","topic":"Trigonometry","difficulty":2,"question_text":"cos²θ−sin²θ=","options":["cos2θ","1","0","sin2θ"],"correct_index":0,"explanation":"Double angle identity: cos2θ."},
  {"subject":"Mathematics","topic":"Trigonometry","difficulty":1,"question_text":"In a right triangle with tanA=3/4, sinA=","options":["3/5","4/5","3/4","5/3"],"correct_index":0,"explanation":"Hypotenuse=5; sinA=3/5."},
  {"subject":"Mathematics","topic":"Trigonometry","difficulty":2,"question_text":"General solution of sinθ=1/2 is:","options":["nπ+(−1)ⁿπ/6","nπ+π/6","2nπ±π/6","nπ/6"],"correct_index":0,"explanation":"General solution of sinθ=sinα: θ=nπ+(−1)ⁿα; α=π/6."},
  {"subject":"Mathematics","topic":"Trigonometry","difficulty":2,"question_text":"sin2A=2sinAcosA. Find sin120°.","options":["√3/2","1/2","1","−√3/2"],"correct_index":0,"explanation":"sin120°=sin(180°−60°)=sin60°=√3/2."},
  {"subject":"Mathematics","topic":"Trigonometry","difficulty":3,"question_text":"A tower 100m tall casts a shadow of 100/√3 m. The sun's elevation angle is:","options":["60°","30°","45°","75°"],"correct_index":0,"explanation":"tanθ=100/(100/√3)=√3 → θ=60°."},
  {"subject":"Mathematics","topic":"Trigonometry","difficulty":1,"question_text":"cos(π)=","options":["−1","0","1","−√3/2"],"correct_index":0,"explanation":"cos180°=−1."},
  {"subject":"Mathematics","topic":"Trigonometry","difficulty":2,"question_text":"sin²A+cos²A=","options":["1","0","2","sinA"],"correct_index":0,"explanation":"Fundamental Pythagorean identity."},
  # --- Mathematics: Analytical Geometry ---
  {"subject":"Mathematics","topic":"Analytical Geometry","difficulty":1,"question_text":"Distance between (3,4) and (0,0) is:","options":["5","7","4","3"],"correct_index":0,"explanation":"√(9+16)=5."},
  {"subject":"Mathematics","topic":"Analytical Geometry","difficulty":2,"question_text":"Centre of x²+y²−6x+4y−3=0 is:","options":["(3,−2)","(−3,2)","(6,−4)","(3,2)"],"correct_index":0,"explanation":"Complete the square: (x−3)²+(y+2)²=16; centre=(3,−2)."},
  {"subject":"Mathematics","topic":"Analytical Geometry","difficulty":2,"question_text":"Slope of line 3x−4y+7=0 is:","options":["3/4","−4/3","4/3","−3/4"],"correct_index":0,"explanation":"y=(3/4)x+7/4; slope=3/4."},
  {"subject":"Mathematics","topic":"Analytical Geometry","difficulty":3,"question_text":"Eccentricity of ellipse with semi-major axis 5 and semi-minor axis 3 is:","options":["4/5","3/5","2/5","1/5"],"correct_index":0,"explanation":"c=√(25−9)=4; e=c/a=4/5."},
  {"subject":"Mathematics","topic":"Analytical Geometry","difficulty":2,"question_text":"Parabola y²=12x has focus at:","options":["(3,0)","(0,3)","(12,0)","(−3,0)"],"correct_index":0,"explanation":"4a=12→a=3; focus=(3,0)."},
  {"subject":"Mathematics","topic":"Analytical Geometry","difficulty":1,"question_text":"Midpoint of (4,6) and (2,2) is:","options":["(3,4)","(6,8)","(2,4)","(3,2)"],"correct_index":0,"explanation":"((4+2)/2,(6+2)/2)=(3,4)."},
  {"subject":"Mathematics","topic":"Analytical Geometry","difficulty":2,"question_text":"For perpendicular lines, m₁×m₂=","options":["−1","0","1","∞"],"correct_index":0,"explanation":"Condition for perpendicularity: m₁m₂=−1."},
  {"subject":"Mathematics","topic":"Analytical Geometry","difficulty":2,"question_text":"The equation of a circle with centre (2,3) and radius 4 is:","options":["(x−2)²+(y−3)²=16","(x+2)²+(y+3)²=16","x²+y²=16","(x−2)²+(y−3)²=4"],"correct_index":0,"explanation":"Standard form: (x−h)²+(y−k)²=r²."},
  # --- Mathematics: Statistics & Probability ---
  {"subject":"Mathematics","topic":"Statistics & Probability","difficulty":1,"question_text":"P(exactly 2 heads in 3 coin tosses)=","options":["3/8","1/2","1/4","1/8"],"correct_index":0,"explanation":"³C₂×(1/2)³=3/8."},
  {"subject":"Mathematics","topic":"Statistics & Probability","difficulty":2,"question_text":"Two dice thrown; P(sum=7)=","options":["1/6","5/36","7/36","1/4"],"correct_index":0,"explanation":"6 favourable/36 total=1/6."},
  {"subject":"Mathematics","topic":"Statistics & Probability","difficulty":2,"question_text":"P(A)=0.4, P(B)=0.3, P(A∩B)=0.1. P(A∪B)=","options":["0.6","0.7","0.5","0.8"],"correct_index":0,"explanation":"0.4+0.3−0.1=0.6."},
  {"subject":"Mathematics","topic":"Statistics & Probability","difficulty":2,"question_text":"Variance of 2,4,6,8,10 is:","options":["8","4","6","10"],"correct_index":0,"explanation":"Mean=6; deviations²: 16,4,0,4,16; variance=40/5=8."},
  {"subject":"Mathematics","topic":"Statistics & Probability","difficulty":1,"question_text":"Mean of first n natural numbers is:","options":["(n+1)/2","n/2","n","n(n+1)/2"],"correct_index":0,"explanation":"Sum=n(n+1)/2; mean=(n+1)/2."},
  {"subject":"Mathematics","topic":"Statistics & Probability","difficulty":3,"question_text":"P(B|A)=0.7, P(A)=0.4, P(B)=0.5. P(A|B)=","options":["0.56","0.28","0.70","0.40"],"correct_index":0,"explanation":"P(A|B)=P(B|A)P(A)/P(B)=0.7×0.4/0.5=0.56."},
  # --- Mathematics: Vector Algebra ---
  {"subject":"Mathematics","topic":"Vector Algebra","difficulty":1,"question_text":"a⃗=(2,3), b⃗=(4,−1). a⃗+b⃗=","options":["(6,2)","(2,4)","(6,−4)","(−2,4)"],"correct_index":0,"explanation":"Component-wise: (6,2)."},
  {"subject":"Mathematics","topic":"Vector Algebra","difficulty":2,"question_text":"Dot product of (1,2,3) and (4,−1,2)=","options":["8","12","4","10"],"correct_index":0,"explanation":"4−2+6=8."},
  {"subject":"Mathematics","topic":"Vector Algebra","difficulty":2,"question_text":"Magnitude of 3î+4ĵ is:","options":["5","7","3","4"],"correct_index":0,"explanation":"√(9+16)=5."},
  {"subject":"Mathematics","topic":"Vector Algebra","difficulty":2,"question_text":"Unit vector along î+ĵ is:","options":["(î+ĵ)/√2","î+ĵ","(î+ĵ)/2","√2(î+ĵ)"],"correct_index":0,"explanation":"Magnitude=√2; unit vector=(î+ĵ)/√2."},
  {"subject":"Mathematics","topic":"Vector Algebra","difficulty":3,"question_text":"a⃗·b⃗=|a⃗||b⃗| implies angle between them is:","options":["0°","90°","180°","45°"],"correct_index":0,"explanation":"cosθ=1 → θ=0°."},
  {"subject":"Mathematics","topic":"Vector Algebra","difficulty":2,"question_text":"|a⃗×b⃗|=0 implies a⃗ and b⃗ are:","options":["Parallel","Perpendicular","Equal","Opposite"],"correct_index":0,"explanation":"sinθ=0 → θ=0° or 180°; vectors are parallel."},
  # --- General Ability: Physics ---
  {"subject":"General Ability","topic":"Physics","difficulty":1,"question_text":"A 2 kg mass at 5 m/s has kinetic energy:","options":["25 J","10 J","50 J","5 J"],"correct_index":0,"explanation":"KE=½mv²=½×2×25=25 J."},
  {"subject":"General Ability","topic":"Physics","difficulty":1,"question_text":"SI unit of force is:","options":["Newton","Joule","Watt","Pascal"],"correct_index":0,"explanation":"1 N=1 kg·m/s²."},
  {"subject":"General Ability","topic":"Physics","difficulty":2,"question_text":"R=5Ω, I=2A. Power dissipated=","options":["20 W","10 W","5 W","40 W"],"correct_index":0,"explanation":"P=I²R=4×5=20 W."},
  {"subject":"General Ability","topic":"Physics","difficulty":2,"question_text":"Frequency=500 Hz, wavelength=0.6 m. Wave speed=","options":["300 m/s","500 m/s","0.6 m/s","833 m/s"],"correct_index":0,"explanation":"v=fλ=500×0.6=300 m/s."},
  {"subject":"General Ability","topic":"Physics","difficulty":2,"question_text":"Convex lens f=20 cm; object at 30 cm. Image distance=","options":["60 cm","30 cm","20 cm","40 cm"],"correct_index":0,"explanation":"1/v+1/30=1/20 → 1/v=1/20−1/30=1/60 → v=60 cm."},
  {"subject":"General Ability","topic":"Physics","difficulty":3,"question_text":"50 kg person in lift accelerating up at 2 m/s² (g=10). Normal force=","options":["600 N","500 N","400 N","700 N"],"correct_index":0,"explanation":"N=m(g+a)=50×12=600 N."},
  {"subject":"General Ability","topic":"Physics","difficulty":1,"question_text":"Light travels fastest in:","options":["Vacuum","Water","Glass","Air"],"correct_index":0,"explanation":"Speed of light in vacuum ≈3×10⁸ m/s."},
  {"subject":"General Ability","topic":"Physics","difficulty":2,"question_text":"Half-life=20 years. After 60 years, fraction remaining=","options":["1/8","1/4","1/2","1/16"],"correct_index":0,"explanation":"3 half-lives: (1/2)³=1/8."},
  {"subject":"General Ability","topic":"Physics","difficulty":1,"question_text":"Boiling point of water at standard pressure=","options":["100°C","0°C","37°C","200°C"],"correct_index":0,"explanation":"100°C=373 K=212°F at 1 atm."},
  {"subject":"General Ability","topic":"Physics","difficulty":2,"question_text":"Projectile fired at 45° for maximum range. If u=20 m/s and g=10, max range=","options":["40 m","20 m","80 m","10 m"],"correct_index":0,"explanation":"R=u²sin2θ/g=400×1/10=40 m."},
  # --- General Ability: Chemistry ---
  {"subject":"General Ability","topic":"Chemistry","difficulty":1,"question_text":"Atomic number of Carbon=","options":["6","12","8","4"],"correct_index":0,"explanation":"6 protons."},
  {"subject":"General Ability","topic":"Chemistry","difficulty":1,"question_text":"pH of neutral solution at 25°C=","options":["7","14","0","1"],"correct_index":0,"explanation":"[H⁺]=[OH⁻]=10⁻⁷ M."},
  {"subject":"General Ability","topic":"Chemistry","difficulty":2,"question_text":"Zn+H₂SO₄→ produces which gas?","options":["H₂","O₂","SO₂","CO₂"],"correct_index":0,"explanation":"Zn+H₂SO₄→ZnSO₄+H₂↑."},
  {"subject":"General Ability","topic":"Chemistry","difficulty":1,"question_text":"Molar mass of H₂SO₄=","options":["98 g/mol","80 g/mol","96 g/mol","100 g/mol"],"correct_index":0,"explanation":"2+32+64=98 g/mol."},
  {"subject":"General Ability","topic":"Chemistry","difficulty":2,"question_text":"Bond in NaCl is:","options":["Ionic","Covalent","Metallic","Van der Waals"],"correct_index":0,"explanation":"Na⁺ and Cl⁻ form ionic bond."},
  {"subject":"General Ability","topic":"Chemistry","difficulty":1,"question_text":"Most abundant gas in Earth's atmosphere=","options":["Nitrogen","Oxygen","CO₂","Argon"],"correct_index":0,"explanation":"N₂≈78% of atmosphere."},
  {"subject":"General Ability","topic":"Chemistry","difficulty":2,"question_text":"Noble gases are unreactive because they have:","options":["Complete outer shells","Low mass","High boiling points","No protons"],"correct_index":0,"explanation":"Full outermost electron shells make them stable."},
  {"subject":"General Ability","topic":"Chemistry","difficulty":2,"question_text":"Rusting of iron is: Fe₂O₃·xH₂O. This is:","options":["Oxidation","Reduction","Sublimation","Decomposition"],"correct_index":0,"explanation":"Iron loses electrons (oxidation) in the presence of O₂ and H₂O."},
  {"subject":"General Ability","topic":"Chemistry","difficulty":3,"question_text":"0.5 mol NaOH contains how many OH⁻ ions?","options":["3.01×10²³","6.02×10²³","1.5×10²³","12×10²³"],"correct_index":0,"explanation":"0.5×6.02×10²³=3.01×10²³."},
  # --- General Ability: History ---
  {"subject":"General Ability","topic":"History","difficulty":1,"question_text":"World War II ended in:","options":["1945","1944","1918","1939"],"correct_index":0,"explanation":"Germany surrendered May 1945; Japan September 1945."},
  {"subject":"General Ability","topic":"History","difficulty":1,"question_text":"UN was established in:","options":["1945","1919","1947","1960"],"correct_index":0,"explanation":"UN Charter signed June 26, 1945; effective Oct 24, 1945."},
  {"subject":"General Ability","topic":"History","difficulty":2,"question_text":"The French Revolution began in:","options":["1789","1776","1804","1815"],"correct_index":0,"explanation":"Storming of the Bastille: July 14, 1789."},
  {"subject":"General Ability","topic":"History","difficulty":2,"question_text":"Battle of Waterloo (1815) ended the rule of:","options":["Napoleon","Louis XVIII","Wellington","Bismarck"],"correct_index":0,"explanation":"Napoleon was decisively defeated at Waterloo on June 18, 1815."},
  {"subject":"General Ability","topic":"History","difficulty":1,"question_text":"India-Pakistan partition occurred in:","options":["1947","1950","1945","1948"],"correct_index":0,"explanation":"August 14–15, 1947 under the Indian Independence Act."},
  {"subject":"General Ability","topic":"History","difficulty":2,"question_text":"Who was the first UN Secretary-General?","options":["Trygve Lie","Dag Hammarskjöld","U Thant","Kurt Waldheim"],"correct_index":0,"explanation":"Trygve Lie of Norway: 1946–1952."},
  {"subject":"General Ability","topic":"History","difficulty":2,"question_text":"The Cold War was primarily between:","options":["USA and USSR","USA and China","UK and USSR","Germany and USA"],"correct_index":0,"explanation":"Cold War (1947–1991) was the ideological rivalry between the US-led West and Soviet-led East."},
  {"subject":"General Ability","topic":"History","difficulty":1,"question_text":"D-Day (June 6, 1944) refers to:","options":["Allied invasion of Normandy","Pearl Harbor attack","Hiroshima bombing","VE Day"],"correct_index":0,"explanation":"Operation Overlord — the Allied amphibious landing in Normandy, France."},
  # --- General Ability: Geography ---
  {"subject":"General Ability","topic":"Geography","difficulty":1,"question_text":"World's highest peak is in:","options":["Nepal","India","China","Bhutan"],"correct_index":0,"explanation":"Everest (8,848.86 m) is on the Nepal-China border; accessed from Nepal."},
  {"subject":"General Ability","topic":"Geography","difficulty":1,"question_text":"Largest continent is:","options":["Asia","Africa","North America","Europe"],"correct_index":0,"explanation":"Asia covers ~44.6 million km²."},
  {"subject":"General Ability","topic":"Geography","difficulty":2,"question_text":"International Date Line follows approximately:","options":["180° meridian","0° meridian","90°E","90°W"],"correct_index":0,"explanation":"Runs along 180° longitude in the Pacific Ocean."},
  {"subject":"General Ability","topic":"Geography","difficulty":1,"question_text":"Country with longest coastline:","options":["Canada","Russia","Australia","USA"],"correct_index":0,"explanation":"Canada: ~202,080 km coastline."},
  {"subject":"General Ability","topic":"Geography","difficulty":2,"question_text":"Strait of Hormuz connects Persian Gulf to:","options":["Arabian Sea","Red Sea","Caspian Sea","Indian Ocean"],"correct_index":0,"explanation":"Connects via Gulf of Oman to the Arabian Sea."},
  {"subject":"General Ability","topic":"Geography","difficulty":2,"question_text":"Amazon River flows primarily through:","options":["Brazil","Argentina","Peru","Colombia"],"correct_index":0,"explanation":"The Amazon (largest by discharge) flows through Brazil to the Atlantic."},
  # --- General Ability: English ---
  {"subject":"General Ability","topic":"English","difficulty":1,"question_text":"Antonym of 'benevolent' is:","options":["Malevolent","Generous","Kind","Philanthropic"],"correct_index":0,"explanation":"Benevolent=wishing good; malevolent=wishing harm."},
  {"subject":"General Ability","topic":"English","difficulty":2,"question_text":"Correct sentence using 'neither...nor':","options":["She neither wrote nor spoke.","She neither wrote or spoke.","She neither wrote nor speak.","She not wrote nor spoke."],"correct_index":0,"explanation":"'Neither...nor' pair with parallel verbs."},
  {"subject":"General Ability","topic":"English","difficulty":1,"question_text":"Synonym of 'ubiquitous' is:","options":["Omnipresent","Rare","Absent","Unique"],"correct_index":0,"explanation":"Ubiquitous=appearing everywhere; omnipresent."},
  {"subject":"General Ability","topic":"English","difficulty":2,"question_text":"Passive of 'The teacher taught the students':","options":["The students were taught by the teacher.","The students are taught by the teacher.","The students taught by the teacher.","The teacher was taught."],"correct_index":0,"explanation":"Object→subject, 'were'+past participle+'by'+agent."},
  {"subject":"General Ability","topic":"English","difficulty":1,"question_text":"'Once in a blue moon' means:","options":["Very rarely","Every month","During full moon","Frequently"],"correct_index":0,"explanation":"Idiom for 'very rarely'."},
  {"subject":"General Ability","topic":"English","difficulty":1,"question_text":"The news ___ shocking. (is/are)","options":["is","are","were","have"],"correct_index":0,"explanation":"'News' is uncountable → singular verb 'is'."},
  {"subject":"General Ability","topic":"English","difficulty":2,"question_text":"Correctly spelled word:","options":["Conscientious","Conscienscious","Consciencious","Concientious"],"correct_index":0,"explanation":"Conscientious: thorough and careful."},
  # --- General Ability: General Science ---
  {"subject":"General Ability","topic":"General Science","difficulty":1,"question_text":"Human heart has how many chambers?","options":["4","2","3","6"],"correct_index":0,"explanation":"Right/left atria and right/left ventricles."},
  {"subject":"General Ability","topic":"General Science","difficulty":1,"question_text":"Largest planet in Solar System:","options":["Jupiter","Saturn","Uranus","Neptune"],"correct_index":0,"explanation":"Jupiter — mass > all other planets combined."},
  {"subject":"General Ability","topic":"General Science","difficulty":1,"question_text":"Photosynthesis occurs in:","options":["Chloroplast","Mitochondria","Nucleus","Ribosome"],"correct_index":0,"explanation":"Chloroplasts contain chlorophyll for light capture."},
  {"subject":"General Ability","topic":"General Science","difficulty":1,"question_text":"Normal human blood pH is approximately:","options":["7.4","6.8","8.0","7.0"],"correct_index":0,"explanation":"Normal range 7.35–7.45 (slightly alkaline)."},
  {"subject":"General Ability","topic":"General Science","difficulty":2,"question_text":"Vitamin essential for blood clotting:","options":["Vitamin K","Vitamin C","Vitamin D","Vitamin B12"],"correct_index":0,"explanation":"Vitamin K is required for synthesis of clotting factors II, VII, IX, X."},
  {"subject":"General Ability","topic":"General Science","difficulty":1,"question_text":"Sound travels fastest in:","options":["Solids","Liquids","Gases","Vacuum"],"correct_index":0,"explanation":"Speed in steel ~5100 m/s vs air ~340 m/s."},
  # --- General Ability: Current Events ---
  {"subject":"General Ability","topic":"Current Events","difficulty":1,"question_text":"The headquarters of ISRO is located in:","options":["Bengaluru","New Delhi","Mumbai","Chennai"],"correct_index":0,"explanation":"Indian Space Research Organisation is headquartered in Bengaluru (Bangalore)."},
  {"subject":"General Ability","topic":"Current Events","difficulty":1,"question_text":"India's first indigenous aircraft carrier is:","options":["INS Vikrant","INS Viraat","INS Vikramaditya","INS Arihant"],"correct_index":0,"explanation":"INS Vikrant was commissioned in September 2022 — India's first domestically built aircraft carrier."},
  {"subject":"General Ability","topic":"Current Events","difficulty":2,"question_text":"G20 is a forum of how many member countries?","options":["20","19","21","25"],"correct_index":0,"explanation":"G20 comprises 19 countries + European Union = 20 members."},
  {"subject":"General Ability","topic":"Current Events","difficulty":1,"question_text":"Operation Sindoor (2025) was conducted by India against:","options":["Pakistan","China","Nepal","Bangladesh"],"correct_index":0,"explanation":"Operation Sindoor was India's military strike against terrorist infrastructure in Pakistan following the Pahalgam attack."},
  {"subject":"General Ability","topic":"Current Events","difficulty":2,"question_text":"The 2024 Paris Olympics were the ___ Summer Olympics.","options":["33rd","32nd","30th","31st"],"correct_index":0,"explanation":"Paris 2024 was the 33rd Summer Olympic Games."},
]

# ---------------------------------------------------------------------------
# JEE questions
# ---------------------------------------------------------------------------
JEE = [
  # Physics: Mechanics
  {"subject":"Physics","topic":"Mechanics","difficulty":1,"question_text":"A ball is thrown vertically upward with u=20 m/s. Max height reached (g=10 m/s²):","options":["20 m","40 m","10 m","5 m"],"correct_index":0,"explanation":"H=u²/2g=400/20=20 m."},
  {"subject":"Physics","topic":"Mechanics","difficulty":2,"question_text":"A 5 kg block on a frictionless surface is pushed by F=15 N. Acceleration=","options":["3 m/s²","5 m/s²","15 m/s²","1 m/s²"],"correct_index":0,"explanation":"a=F/m=15/5=3 m/s²."},
  {"subject":"Physics","topic":"Mechanics","difficulty":2,"question_text":"Momentum of 4 kg object moving at 6 m/s:","options":["24 kg·m/s","10 kg·m/s","2.4 kg·m/s","12 kg·m/s"],"correct_index":0,"explanation":"p=mv=4×6=24 kg·m/s."},
  {"subject":"Physics","topic":"Mechanics","difficulty":3,"question_text":"A satellite in circular orbit at height R above Earth's surface (R=Earth's radius). Orbital speed vs escape speed ratio:","options":["1/√2","1/2","√2","2"],"correct_index":0,"explanation":"At r=2R: v_orbital=√(GM/2R); v_escape=√(2GM/2R). Ratio=1/√2."},
  {"subject":"Physics","topic":"Mechanics","difficulty":2,"question_text":"Work done by force F=5î+3ĵ N over displacement d=2î+4ĵ m:","options":["22 J","26 J","10 J","16 J"],"correct_index":0,"explanation":"W=F·d=5×2+3×4=10+12=22 J."},
  {"subject":"Physics","topic":"Mechanics","difficulty":2,"question_text":"Angular momentum L=Iω. If I=2 kg·m² and ω=4 rad/s, L=","options":["8 kg·m²/s","6 kg·m²/s","2 kg·m²/s","0.5 kg·m²/s"],"correct_index":0,"explanation":"L=2×4=8 kg·m²/s."},
  {"subject":"Physics","topic":"Mechanics","difficulty":1,"question_text":"An object in uniform circular motion has:","options":["Constant speed, changing direction","Constant velocity","No acceleration","Increasing speed"],"correct_index":0,"explanation":"Speed is constant but direction changes, so velocity and acceleration change."},
  {"subject":"Physics","topic":"Mechanics","difficulty":3,"question_text":"Two balls of mass m and 2m collide elastically. Ball m is at rest; 2m moves at v. After collision, velocity of m=","options":["4v/3","2v/3","v","0"],"correct_index":0,"explanation":"For elastic collision: v₁'=(m₁−m₂)v/(m₁+m₂). Here m moves, m₁=2m (moving), m₂=m (rest). v_m'=2×2m×v/(3m)=4v/3."},
  {"subject":"Physics","topic":"Mechanics","difficulty":2,"question_text":"A spring of k=200 N/m is compressed by 0.1 m. Potential energy stored=","options":["1 J","2 J","0.5 J","20 J"],"correct_index":0,"explanation":"PE=½kx²=½×200×0.01=1 J."},
  {"subject":"Physics","topic":"Mechanics","difficulty":1,"question_text":"Centripetal acceleration for circular motion of radius r and speed v is:","options":["v²/r","v/r","vr","v²r"],"correct_index":0,"explanation":"a_c=v²/r directed toward center."},
  # Physics: Thermodynamics
  {"subject":"Physics","topic":"Thermodynamics","difficulty":1,"question_text":"First law of thermodynamics states:","options":["ΔU=Q−W","ΔU=Q+W","Q=W","ΔU=0"],"correct_index":0,"explanation":"Energy conservation: internal energy change = heat added − work done by system."},
  {"subject":"Physics","topic":"Thermodynamics","difficulty":2,"question_text":"An ideal gas expands isothermally. Work done by gas=","options":["nRT ln(V₂/V₁)","nRΔT","P(V₂−V₁)","0"],"correct_index":0,"explanation":"For isothermal process of ideal gas: W=nRT ln(V₂/V₁)."},
  {"subject":"Physics","topic":"Thermodynamics","difficulty":2,"question_text":"Efficiency of Carnot engine with T_H=500K and T_C=300K:","options":["40%","60%","50%","20%"],"correct_index":0,"explanation":"η=(1−T_C/T_H)×100=(1−300/500)×100=40%."},
  {"subject":"Physics","topic":"Thermodynamics","difficulty":1,"question_text":"At absolute zero (0 K), entropy of a perfect crystal is:","options":["Zero","Maximum","One","Undefined"],"correct_index":0,"explanation":"Third law of thermodynamics: S=0 at T=0 K for a perfect crystal."},
  {"subject":"Physics","topic":"Thermodynamics","difficulty":3,"question_text":"In adiabatic process, Q=0. For ideal gas: PVᵞ=const. For diatomic gas, γ=","options":["7/5","5/3","4/3","1"],"correct_index":0,"explanation":"γ=Cp/Cv; diatomic: Cv=5R/2, Cp=7R/2, γ=7/5=1.4."},
  {"subject":"Physics","topic":"Thermodynamics","difficulty":2,"question_text":"Specific heat capacity of water is 4200 J/(kg·K). Heat to raise 2 kg by 5°C:","options":["42000 J","21000 J","8400 J","4200 J"],"correct_index":0,"explanation":"Q=mcΔT=2×4200×5=42000 J."},
  # Physics: Electrostatics
  {"subject":"Physics","topic":"Electrostatics","difficulty":1,"question_text":"Coulomb's law: F=kq₁q₂/r². If r doubles, F becomes:","options":["F/4","F/2","2F","4F"],"correct_index":0,"explanation":"F∝1/r²; doubling r → F becomes F/4."},
  {"subject":"Physics","topic":"Electrostatics","difficulty":2,"question_text":"Electric field due to a point charge q at distance r: E=","options":["kq/r²","kq/r","kq²/r","kq·r"],"correct_index":0,"explanation":"E=kq/r²; k=9×10⁹ N·m²/C²."},
  {"subject":"Physics","topic":"Electrostatics","difficulty":2,"question_text":"Capacitance of parallel plate capacitor with area A, separation d, dielectric k:","options":["kε₀A/d","ε₀A/d","kε₀d/A","ε₀Ad"],"correct_index":0,"explanation":"C=kε₀A/d where ε₀=8.85×10⁻¹² F/m."},
  {"subject":"Physics","topic":"Electrostatics","difficulty":2,"question_text":"Energy stored in capacitor C at voltage V:","options":["½CV²","CV","CV²","C/V"],"correct_index":0,"explanation":"U=½CV²=Q²/2C=QV/2."},
  {"subject":"Physics","topic":"Electrostatics","difficulty":3,"question_text":"Electric potential at distance r from charge q: V=kq/r. Work to bring charge q₀ from ∞ to r:","options":["kqq₀/r","kq/r","kqq₀/r²","0"],"correct_index":0,"explanation":"W=q₀V=kqq₀/r."},
  # Physics: Current Electricity
  {"subject":"Physics","topic":"Current Electricity","difficulty":1,"question_text":"Three resistors 2Ω, 3Ω, 6Ω in parallel. Equivalent resistance:","options":["1 Ω","11 Ω","0.5 Ω","3.67 Ω"],"correct_index":0,"explanation":"1/R=1/2+1/3+1/6=3/6+2/6+1/6=1. R=1Ω."},
  {"subject":"Physics","topic":"Current Electricity","difficulty":2,"question_text":"EMF=12V, internal resistance=2Ω, external R=4Ω. Current through circuit:","options":["2 A","3 A","1.5 A","6 A"],"correct_index":0,"explanation":"I=EMF/(R+r)=12/6=2 A."},
  {"subject":"Physics","topic":"Current Electricity","difficulty":2,"question_text":"Kirchhoff's Current Law states:","options":["Sum of currents at a node=0","Sum of voltages in loop=0","V=IR","P=IV"],"correct_index":0,"explanation":"KCL: algebraic sum of currents entering/leaving a junction=0."},
  {"subject":"Physics","topic":"Current Electricity","difficulty":1,"question_text":"Resistivity of a material depends on:","options":["Material and temperature","Length only","Area only","Current"],"correct_index":0,"explanation":"Resistivity ρ is an intrinsic property depending on material and temperature."},
  {"subject":"Physics","topic":"Current Electricity","difficulty":2,"question_text":"Power dissipated in resistor R carrying current I:","options":["I²R","IR","I/R","IR²"],"correct_index":0,"explanation":"P=I²R=V²/R=VI."},
  # Physics: Magnetism
  {"subject":"Physics","topic":"Magnetism","difficulty":1,"question_text":"Force on charge q moving with velocity v in magnetic field B: F=","options":["qv×B","qB/v","qvB","q/vB"],"correct_index":0,"explanation":"Lorentz magnetic force: F=q(v×B). Magnitude: F=qvBsinθ."},
  {"subject":"Physics","topic":"Magnetism","difficulty":2,"question_text":"A current-carrying conductor in a magnetic field experiences a force called:","options":["Ampere force","Lorentz force","Coulomb force","Gravitational force"],"correct_index":0,"explanation":"The force on a current-carrying conductor in a magnetic field is called the Ampere force (F=IL×B)."},
  {"subject":"Physics","topic":"Magnetism","difficulty":2,"question_text":"The SI unit of magnetic field strength (B) is:","options":["Tesla","Gauss","Ampere/m","Weber"],"correct_index":0,"explanation":"SI unit of magnetic flux density B is Tesla (T). 1 T=10,000 Gauss."},
  {"subject":"Physics","topic":"Magnetism","difficulty":3,"question_text":"A proton moves perpendicular to B=0.1 T at v=10⁶ m/s. Radius of circular path (m_p=1.67×10⁻²⁷ kg):","options":["0.104 m","0.01 m","1.04 m","0.001 m"],"correct_index":0,"explanation":"r=mv/(qB)=1.67×10⁻²⁷×10⁶/(1.6×10⁻¹⁹×0.1)≈0.104 m."},
  # Physics: Optics
  {"subject":"Physics","topic":"Optics","difficulty":1,"question_text":"Refractive index μ=c/v. If μ=1.5 for glass, speed of light in glass=","options":["2×10⁸ m/s","1.5×10⁸ m/s","3×10⁸ m/s","4.5×10⁸ m/s"],"correct_index":0,"explanation":"v=c/μ=3×10⁸/1.5=2×10⁸ m/s."},
  {"subject":"Physics","topic":"Optics","difficulty":2,"question_text":"Lens formula: 1/v−1/u=1/f. Object at u=−30 cm, f=10 cm. Image position:","options":["15 cm","−15 cm","30 cm","10 cm"],"correct_index":0,"explanation":"1/v=1/f+1/u=1/10+1/(−30)=3/30−1/30=2/30; v=15 cm."},
  {"subject":"Physics","topic":"Optics","difficulty":2,"question_text":"Young's double-slit: fringe width β=λD/d. If λ=600nm, D=1m, d=0.3mm, β=","options":["2 mm","0.2 mm","20 mm","0.02 mm"],"correct_index":0,"explanation":"β=600×10⁻⁹×1/(0.3×10⁻³)=2×10⁻³ m=2 mm."},
  {"subject":"Physics","topic":"Optics","difficulty":1,"question_text":"Total internal reflection occurs when light goes from:","options":["Denser to rarer medium beyond critical angle","Rarer to denser","At any angle","In vacuum"],"correct_index":0,"explanation":"TIR occurs when light in denser medium hits rarer medium at angle ≥ critical angle."},
  {"subject":"Physics","topic":"Optics","difficulty":2,"question_text":"Power of a lens with focal length 25 cm:","options":["4 D","2.5 D","0.25 D","40 D"],"correct_index":0,"explanation":"P=1/f(m)=1/0.25=4 diopters."},
  # Physics: Modern Physics
  {"subject":"Physics","topic":"Modern Physics","difficulty":2,"question_text":"Energy of a photon with frequency ν=6×10¹⁴ Hz (h=6.63×10⁻³⁴ J·s):","options":["3.98×10⁻¹⁹ J","6×10⁻¹⁹ J","1×10⁻¹⁹ J","6.63×10⁻³⁴ J"],"correct_index":0,"explanation":"E=hν=6.63×10⁻³⁴×6×10¹⁴≈3.98×10⁻¹⁹ J."},
  {"subject":"Physics","topic":"Modern Physics","difficulty":2,"question_text":"In photoelectric effect, stopping potential depends on:","options":["Frequency of light","Intensity of light","Both","Neither"],"correct_index":0,"explanation":"Stopping potential depends on frequency (not intensity). Higher frequency → higher KE_max → higher stopping potential."},
  {"subject":"Physics","topic":"Modern Physics","difficulty":3,"question_text":"de Broglie wavelength λ=h/mv. For electron at v=10⁶ m/s (m=9.1×10⁻³¹ kg):","options":["0.727 nm","0.073 nm","7.27 nm","72.7 pm"],"correct_index":0,"explanation":"λ=6.63×10⁻³⁴/(9.1×10⁻³¹×10⁶)=7.27×10⁻¹⁰ m=0.727 nm."},
  {"subject":"Physics","topic":"Modern Physics","difficulty":1,"question_text":"Nucleus of an atom contains:","options":["Protons and neutrons","Protons and electrons","Neutrons only","Electrons"],"correct_index":0,"explanation":"The nucleus contains protons (positive) and neutrons (neutral). Electrons orbit outside."},
  # Chemistry: Organic
  {"subject":"Chemistry","topic":"Organic Chemistry","difficulty":1,"question_text":"CH₄ (methane) belongs to the homologous series of:","options":["Alkanes","Alkenes","Alkynes","Alcohols"],"correct_index":0,"explanation":"Methane is the simplest alkane (CₙH₂ₙ₊₂), saturated hydrocarbons with single C-C bonds."},
  {"subject":"Chemistry","topic":"Organic Chemistry","difficulty":2,"question_text":"The IUPAC name of CH₃-CH₂-OH is:","options":["Ethanol","Methanol","Propanol","Ethanoic acid"],"correct_index":0,"explanation":"Two carbon chain with -OH group: eth+anol=Ethanol."},
  {"subject":"Chemistry","topic":"Organic Chemistry","difficulty":2,"question_text":"Benzene (C₆H₆) undergoes which type of reaction preferentially?","options":["Electrophilic substitution","Nucleophilic addition","Free radical addition","Elimination"],"correct_index":0,"explanation":"Benzene's aromatic ring prefers electrophilic substitution (nitration, sulfonation, halogenation) to preserve aromaticity."},
  {"subject":"Chemistry","topic":"Organic Chemistry","difficulty":3,"question_text":"In Lucas test, 2° alcohols react with anhydrous ZnCl₂/HCl at room temperature:","options":["Slowly (turbidity in 5 min)","Immediately","No reaction","Only on heating"],"correct_index":0,"explanation":"Lucas test: 3° alcohols react immediately; 2° slowly (~5 min); 1° alcohols require heating."},
  {"subject":"Chemistry","topic":"Organic Chemistry","difficulty":2,"question_text":"Aldol condensation occurs between:","options":["Two carbonyl compounds with α-H","Alkene and water","Alcohol and acid","Amine and carboxylic acid"],"correct_index":0,"explanation":"Aldol condensation: enolate of one carbonyl attacks the carbonyl carbon of another, forming β-hydroxy carbonyl compound."},
  {"subject":"Chemistry","topic":"Organic Chemistry","difficulty":1,"question_text":"Functional group in carboxylic acids is:","options":["−COOH","−OH","−CHO","−CO−"],"correct_index":0,"explanation":"Carboxylic acids contain −COOH (carboxyl group)."},
  {"subject":"Chemistry","topic":"Organic Chemistry","difficulty":2,"question_text":"Which reaction converts alkene to alkane?","options":["Hydrogenation","Halogenation","Oxidation","Elimination"],"correct_index":0,"explanation":"Hydrogenation adds H₂ across C=C double bond (Ni/Pt catalyst) to form alkane."},
  {"subject":"Chemistry","topic":"Organic Chemistry","difficulty":2,"question_text":"The hybridization of carbon in ethyne (C₂H₂) is:","options":["sp","sp²","sp³","sp³d"],"correct_index":0,"explanation":"Ethyne has a triple bond; each carbon is sp hybridized (linear geometry, 180°)."},
  # Chemistry: Inorganic
  {"subject":"Chemistry","topic":"Inorganic Chemistry","difficulty":1,"question_text":"The most electronegative element is:","options":["Fluorine","Oxygen","Chlorine","Nitrogen"],"correct_index":0,"explanation":"Fluorine (F) has the highest electronegativity (4.0 on Pauling scale)."},
  {"subject":"Chemistry","topic":"Inorganic Chemistry","difficulty":2,"question_text":"Electronic configuration of Fe (Z=26) is:","options":["[Ar]3d⁶4s²","[Ar]4s²3d⁶","[Kr]3d⁶4s²","[Ar]3d⁸"],"correct_index":0,"explanation":"Fe: 1s²2s²2p⁶3s²3p⁶3d⁶4s²=[Ar]3d⁶4s²."},
  {"subject":"Chemistry","topic":"Inorganic Chemistry","difficulty":2,"question_text":"Which period 3 element has the highest ionization energy?","options":["Argon","Sodium","Chlorine","Silicon"],"correct_index":0,"explanation":"Noble gases have highest ionization energies due to complete shells. Ar has the highest in period 3."},
  {"subject":"Chemistry","topic":"Inorganic Chemistry","difficulty":3,"question_text":"In coordination compound [Fe(CN)₆]⁴⁻, the oxidation state of Fe is:","options":["2","3","4","6"],"correct_index":0,"explanation":"CN⁻ has charge −1 each. Total charge=−4. 6×(−1)+Fe=−4 → Fe=+2."},
  {"subject":"Chemistry","topic":"Inorganic Chemistry","difficulty":2,"question_text":"Amphoteric oxides react with both acids and bases. An example is:","options":["Al₂O₃","Na₂O","CO₂","FeO"],"correct_index":0,"explanation":"Aluminium oxide (Al₂O₃) reacts with both HCl and NaOH → amphoteric."},
  {"subject":"Chemistry","topic":"Inorganic Chemistry","difficulty":1,"question_text":"Which family of elements is called halogens?","options":["Group 17","Group 18","Group 1","Group 16"],"correct_index":0,"explanation":"Group 17 elements (F, Cl, Br, I, At) are halogens — reactive nonmetals."},
  {"subject":"Chemistry","topic":"Inorganic Chemistry","difficulty":2,"question_text":"The shape of NH₃ molecule is:","options":["Trigonal pyramidal","Tetrahedral","Trigonal planar","Linear"],"correct_index":0,"explanation":"NH₃ has 3 bond pairs + 1 lone pair; VSEPR: trigonal pyramidal, bond angle ~107°."},
  # Chemistry: Physical
  {"subject":"Chemistry","topic":"Physical Chemistry","difficulty":1,"question_text":"Raoult's Law relates to:","options":["Vapour pressure of solutions","Reaction rates","Electrode potentials","Gas laws"],"correct_index":0,"explanation":"Raoult's Law: vapour pressure of solution = mole fraction × vapour pressure of pure solvent."},
  {"subject":"Chemistry","topic":"Physical Chemistry","difficulty":2,"question_text":"Rate constant of 1st order reaction has units:","options":["s⁻¹","mol·L⁻¹·s⁻¹","L·mol⁻¹·s⁻¹","s"],"correct_index":0,"explanation":"For 1st order: rate=k[A]; k=rate/[A]=(mol·L⁻¹·s⁻¹)/(mol·L⁻¹)=s⁻¹."},
  {"subject":"Chemistry","topic":"Physical Chemistry","difficulty":2,"question_text":"ΔG=ΔH−TΔS. Reaction is spontaneous when:","options":["ΔG<0","ΔG>0","ΔG=0","ΔH>0"],"correct_index":0,"explanation":"Negative ΔG indicates spontaneous process at constant T and P."},
  {"subject":"Chemistry","topic":"Physical Chemistry","difficulty":2,"question_text":"pH of 0.01 M HCl solution is:","options":["2","−2","12","1"],"correct_index":0,"explanation":"HCl is strong acid: [H⁺]=0.01=10⁻² M. pH=−log(10⁻²)=2."},
  {"subject":"Chemistry","topic":"Physical Chemistry","difficulty":3,"question_text":"Faraday's first law: mass deposited∝charge passed. 96500 C deposits how many grams of Ag (M=108)?","options":["108 g","54 g","216 g","1 g"],"correct_index":0,"explanation":"1 Faraday (96500 C) deposits 1 mole of Ag⁺ → 108 g."},
  {"subject":"Chemistry","topic":"Physical Chemistry","difficulty":2,"question_text":"The colligative property that explains why salt lowers the freezing point of water is:","options":["Depression in freezing point","Elevation of boiling point","Osmotic pressure","Vapour pressure lowering"],"correct_index":0,"explanation":"Adding solute lowers the freezing point: ΔTf=Kf×m. This is called cryoscopic depression."},
  # Mathematics: Algebra
  {"subject":"Mathematics","topic":"Algebra","difficulty":2,"question_text":"The number of complex roots of x⁴−1=0 is:","options":["2","4","0","1"],"correct_index":0,"explanation":"x⁴=1 has 4 roots: 1,−1,i,−i. Two are purely imaginary (complex)."},
  {"subject":"Mathematics","topic":"Algebra","difficulty":2,"question_text":"Sum of GP: 1+3+9+...+3⁷=","options":["3280","1093","9841","2187"],"correct_index":0,"explanation":"S=a(rⁿ−1)/(r−1)=1×(3⁸−1)/2=(6561−1)/2=3280."},
  {"subject":"Mathematics","topic":"Algebra","difficulty":1,"question_text":"If A is a 3×3 matrix, det(2A)=","options":["8 det(A)","2 det(A)","4 det(A)","det(A)"],"correct_index":0,"explanation":"det(kA)=kⁿdet(A) for n×n matrix. det(2A)=2³det(A)=8det(A)."},
  {"subject":"Mathematics","topic":"Algebra","difficulty":2,"question_text":"The roots of x²−3x+2=0 are:","options":["1 and 2","−1 and −2","3 and 1","1 and 3"],"correct_index":0,"explanation":"(x−1)(x−2)=0; roots: 1 and 2."},
  # Mathematics: Calculus
  {"subject":"Mathematics","topic":"Calculus","difficulty":2,"question_text":"∫(1/x)dx=","options":["ln|x|+C","x+C","−1/x²+C","log x+C"],"correct_index":0,"explanation":"∫(1/x)dx=ln|x|+C."},
  {"subject":"Mathematics","topic":"Calculus","difficulty":2,"question_text":"d/dx[tan x]=","options":["sec²x","cot²x","cosec²x","−sec²x"],"correct_index":0,"explanation":"d/dx[tanx]=sec²x."},
  {"subject":"Mathematics","topic":"Calculus","difficulty":3,"question_text":"∫₀^1 x²eˣ dx (by parts twice)=","options":["e−2","2e−1","e+1","e−1"],"correct_index":0,"explanation":"∫x²eˣdx=eˣ(x²−2x+2)+C. At x=1: e(1−2+2)=e. At x=0: 1(0−0+2)=2. Result=e−2."},
  # Mathematics: Coordinate Geometry
  {"subject":"Mathematics","topic":"Coordinate Geometry","difficulty":1,"question_text":"Equation of x-axis is:","options":["y=0","x=0","y=x","x+y=0"],"correct_index":0,"explanation":"The x-axis is the line y=0."},
  {"subject":"Mathematics","topic":"Coordinate Geometry","difficulty":2,"question_text":"The foci of ellipse x²/25+y²/16=1 are at:","options":["(±3,0)","(±5,0)","(±4,0)","(0,±3)"],"correct_index":0,"explanation":"a²=25, b²=16; c=√(25−16)=3. Foci at (±3,0)."},
  {"subject":"Mathematics","topic":"Coordinate Geometry","difficulty":2,"question_text":"The directrix of parabola y²=8x is:","options":["x=−2","x=2","y=−2","y=2"],"correct_index":0,"explanation":"y²=4ax → a=2. Directrix: x=−a=−2."},
  {"subject":"Mathematics","topic":"Coordinate Geometry","difficulty":2,"question_text":"Area of triangle with vertices (0,0),(4,0),(0,3):","options":["6","12","3","4"],"correct_index":0,"explanation":"Area=½×base×height=½×4×3=6."},
  # Mathematics: Trigonometry
  {"subject":"Mathematics","topic":"Trigonometry","difficulty":2,"question_text":"cos2A in terms of tanA:","options":["(1−tan²A)/(1+tan²A)","(1+tan²A)/(1−tan²A)","2tanA","1−tan²A"],"correct_index":0,"explanation":"cos2A=(1−tan²A)/(1+tan²A)."},
  {"subject":"Mathematics","topic":"Trigonometry","difficulty":2,"question_text":"The value of tan75°=","options":["2+√3","2−√3","√3","1"],"correct_index":0,"explanation":"tan75°=tan(45°+30°)=(1+1/√3)/(1−1/√3)=(√3+1)/(√3−1)=2+√3."},
  {"subject":"Mathematics","topic":"Trigonometry","difficulty":1,"question_text":"Range of sin x is:","options":["[−1,1]","[0,1]","(−∞,∞)","[0,∞)"],"correct_index":0,"explanation":"sin x oscillates between −1 and 1 inclusive."},
  # Mathematics: Vectors & 3D
  {"subject":"Mathematics","topic":"Vectors & 3D","difficulty":2,"question_text":"The angle between vectors a⃗=î+ĵ and b⃗=ĵ+k̂:","options":["60°","90°","45°","30°"],"correct_index":0,"explanation":"cosθ=a·b/(|a||b|)=1/(√2×√2)=1/2; θ=60°."},
  {"subject":"Mathematics","topic":"Vectors & 3D","difficulty":2,"question_text":"Equation of line through (1,2,3) with direction (2,1,−1):","options":["(x−1)/2=(y−2)/1=(z−3)/(−1)","x/2=y/1=z/(−1)","(x−2)/1=(y−1)/2=(z+1)/3","None"],"correct_index":0,"explanation":"Symmetric form: (x−x₁)/l=(y−y₁)/m=(z−z₁)/n."},
  {"subject":"Mathematics","topic":"Vectors & 3D","difficulty":1,"question_text":"The distance between parallel planes 2x+y+2z=3 and 4x+2y+4z=12 is:","options":["1/2","1","3/2","2"],"correct_index":0,"explanation":"Rewrite 2nd plane: 2x+y+2z=6. Distance=|6−3|/√(4+1+4)=3/3=1."},
  # Mathematics: Statistics & Probability
  {"subject":"Mathematics","topic":"Statistics & Probability","difficulty":2,"question_text":"In Binomial distribution B(n,p), mean=np and variance=","options":["np(1−p)","np","np²","n²p"],"correct_index":0,"explanation":"Variance of binomial distribution = npq = np(1−p)."},
  {"subject":"Mathematics","topic":"Statistics & Probability","difficulty":2,"question_text":"If P(A)=0.6 and A, B are independent with P(B)=0.5, P(A∩B)=","options":["0.3","0.1","0.6","0.5"],"correct_index":0,"explanation":"For independent events: P(A∩B)=P(A)×P(B)=0.6×0.5=0.3."},
  {"subject":"Mathematics","topic":"Statistics & Probability","difficulty":1,"question_text":"Standard deviation of 2,4,4,4,5,5,7,9 is:","options":["2","4","1","3"],"correct_index":0,"explanation":"Mean=5; deviations²: 9,1,1,1,0,0,4,16; variance=32/8=4; SD=2."},
]

# ---------------------------------------------------------------------------
# NEET questions
# ---------------------------------------------------------------------------
NEET = [
  # Physics: Mechanics
  {"subject":"Physics","topic":"Mechanics","difficulty":1,"question_text":"A stone dropped from height h hits ground after time:","options":["√(2h/g)","√(h/g)","2h/g","h/g"],"correct_index":0,"explanation":"h=½gt² → t=√(2h/g)."},
  {"subject":"Physics","topic":"Mechanics","difficulty":2,"question_text":"A 60 kg person runs up stairs of height 5m in 10s. Power developed:","options":["300 W","600 W","150 W","3000 W"],"correct_index":0,"explanation":"P=mgh/t=60×10×5/10=300 W."},
  {"subject":"Physics","topic":"Mechanics","difficulty":2,"question_text":"Law of conservation of momentum holds when:","options":["Net external force=0","Energy is conserved","All forces are conservative","Velocity is constant"],"correct_index":0,"explanation":"Momentum is conserved when net external force on system=0 (Newton's 3rd law consequence)."},
  {"subject":"Physics","topic":"Mechanics","difficulty":1,"question_text":"SI unit of pressure is:","options":["Pascal","Newton","Joule","Watt"],"correct_index":0,"explanation":"1 Pascal=1 N/m²."},
  {"subject":"Physics","topic":"Mechanics","difficulty":2,"question_text":"Escape velocity from Earth's surface (R=6400km, g=9.8 m/s²) ≈","options":["11.2 km/s","8 km/s","9.8 km/s","7.9 km/s"],"correct_index":0,"explanation":"v_e=√(2gR)=√(2×9.8×6.4×10⁶)≈11.2 km/s."},
  # Physics: Thermodynamics
  {"subject":"Physics","topic":"Thermodynamics","difficulty":1,"question_text":"Heat always flows from:","options":["Higher to lower temperature","Lower to higher temperature","Hot to cold and back","No direction preference"],"correct_index":0,"explanation":"2nd law of thermodynamics: heat flows spontaneously from hot to cold."},
  {"subject":"Physics","topic":"Thermodynamics","difficulty":2,"question_text":"A gas is compressed isothermally. Internal energy:","options":["Remains constant","Increases","Decreases","Becomes zero"],"correct_index":0,"explanation":"For ideal gas: internal energy depends only on temperature. Isothermal→T constant→ΔU=0."},
  {"subject":"Physics","topic":"Thermodynamics","difficulty":2,"question_text":"Specific heat at constant pressure Cp vs at constant volume Cv: for ideal gas:","options":["Cp>Cv","Cp<Cv","Cp=Cv","Cp=Cv/γ"],"correct_index":0,"explanation":"Cp=Cv+R. Always Cp>Cv for ideal gases."},
  # Physics: Electrostatics & Magnetism
  {"subject":"Physics","topic":"Electrostatics & Magnetism","difficulty":1,"question_text":"Gauss's law: total electric flux through a closed surface = Q_enc/ε₀. If Q_enc=0:","options":["Flux=0","Flux>0","Flux<0","Cannot determine"],"correct_index":0,"explanation":"If enclosed charge=0, net electric flux=0."},
  {"subject":"Physics","topic":"Electrostatics & Magnetism","difficulty":2,"question_text":"A solenoid with n turns/m carrying current I has magnetic field inside:","options":["μ₀nI","μ₀I/n","nI","μ₀n/I"],"correct_index":0,"explanation":"B=μ₀nI inside a long solenoid."},
  {"subject":"Physics","topic":"Electrostatics & Magnetism","difficulty":2,"question_text":"Faraday's law: induced EMF = −dΦ/dt. Negative sign represents:","options":["Lenz's law (opposing change)","Energy loss","Current direction","Resistance"],"correct_index":0,"explanation":"Negative sign represents Lenz's law: induced EMF opposes the change in flux."},
  # Physics: Optics
  {"subject":"Physics","topic":"Optics","difficulty":1,"question_text":"A concave mirror of focal length 15 cm forms image at 30 cm from mirror. Object distance:","options":["30 cm","15 cm","45 cm","60 cm"],"correct_index":0,"explanation":"Mirror formula: 1/v+1/u=1/f. 1/30+1/u=1/15 → 1/u=1/15−1/30=1/30 → u=30 cm."},
  {"subject":"Physics","topic":"Optics","difficulty":2,"question_text":"Human eye can see objects clearly between near point (25 cm) and far point (∞). This is called:","options":["Range of accommodation","Persistence of vision","Least distance of distinct vision","Visual angle"],"correct_index":0,"explanation":"The range over which the eye can focus by changing lens curvature is the range of accommodation."},
  {"subject":"Physics","topic":"Optics","difficulty":2,"question_text":"Dispersive power of prism depends on:","options":["Material of prism","Angle of prism","Colour of light","Size of prism"],"correct_index":0,"explanation":"Dispersive power=ω=(μᵥ−μᵣ)/(μ_y−1) depends on the material (refractive indices)."},
  # Physics: Modern Physics
  {"subject":"Physics","topic":"Modern Physics","difficulty":2,"question_text":"In α-decay, mass number decreases by:","options":["4","2","1","0"],"correct_index":0,"explanation":"α-particle = ⁴He nucleus; α-decay: A decreases by 4, Z decreases by 2."},
  {"subject":"Physics","topic":"Modern Physics","difficulty":1,"question_text":"X-rays are:","options":["Electromagnetic radiation","Sound waves","Mechanical waves","Particle radiation"],"correct_index":0,"explanation":"X-rays are high-energy electromagnetic radiation (wavelength 0.01–10 nm)."},
  {"subject":"Physics","topic":"Modern Physics","difficulty":3,"question_text":"Energy released in fusion of 1 kg of H to He (binding energy gain ≈7 MeV/nucleon for He):","options":["6.3×10¹⁴ J","6.3×10¹¹ J","4.2×10¹⁴ J","1×10¹⁷ J"],"correct_index":0,"explanation":"1 kg H = 6×10²⁶ nucleons; gain ≈7 MeV×6×10²⁶/4×1.6×10⁻¹³≈6.3×10¹⁴ J."},
  # Chemistry: Organic
  {"subject":"Chemistry","topic":"Organic Chemistry","difficulty":1,"question_text":"Glucose molecular formula is:","options":["C₆H₁₂O₆","C₁₂H₂₂O₁₁","C₆H₁₀O₅","C₃H₆O₃"],"correct_index":0,"explanation":"Glucose (monosaccharide) = C₆H₁₂O₆."},
  {"subject":"Chemistry","topic":"Organic Chemistry","difficulty":2,"question_text":"Hydrolysis of starch by amylase produces:","options":["Maltose then glucose","Fructose","Cellulose","Lactose"],"correct_index":0,"explanation":"Amylase breaks starch → maltose; maltase breaks maltose → glucose."},
  {"subject":"Chemistry","topic":"Organic Chemistry","difficulty":2,"question_text":"Primary structure of a protein refers to:","options":["Sequence of amino acids","Alpha helix structure","Beta sheet structure","3D folding"],"correct_index":0,"explanation":"Primary structure = amino acid sequence held by peptide (covalent) bonds."},
  {"subject":"Chemistry","topic":"Organic Chemistry","difficulty":3,"question_text":"Saponification of ester produces:","options":["Carboxylate + alcohol","Carboxylic acid + alkene","Aldehyde + alcohol","Ketone + water"],"correct_index":0,"explanation":"Ester + NaOH → sodium carboxylate (soap) + alcohol. This is saponification."},
  # Chemistry: Inorganic
  {"subject":"Chemistry","topic":"Inorganic Chemistry","difficulty":1,"question_text":"Which element is essential for chlorophyll in plants?","options":["Magnesium","Iron","Calcium","Potassium"],"correct_index":0,"explanation":"Chlorophyll contains Mg²⁺ at its centre in a porphyrin ring."},
  {"subject":"Chemistry","topic":"Inorganic Chemistry","difficulty":2,"question_text":"Haemoglobin contains which metal?","options":["Iron","Magnesium","Zinc","Copper"],"correct_index":0,"explanation":"Haemoglobin has Fe²⁺ in its haem group which binds oxygen."},
  {"subject":"Chemistry","topic":"Inorganic Chemistry","difficulty":2,"question_text":"Enzyme carbonic anhydrase contains:","options":["Zinc","Magnesium","Iron","Copper"],"correct_index":0,"explanation":"Carbonic anhydrase (CO₂+H₂O↔H₂CO₃) has Zn²⁺ as cofactor."},
  # Chemistry: Physical
  {"subject":"Chemistry","topic":"Physical Chemistry","difficulty":1,"question_text":"Osmosis involves movement of water from:","options":["Low solute to high solute concentration","High to low solute concentration","Equal concentrations","Both directions equally"],"correct_index":0,"explanation":"Water moves from hypotonic (low solute) to hypertonic (high solute) solution across semipermeable membrane."},
  {"subject":"Chemistry","topic":"Physical Chemistry","difficulty":2,"question_text":"Buffer solution resists change in:","options":["pH","Temperature","Pressure","Volume"],"correct_index":0,"explanation":"A buffer solution maintains nearly constant pH upon addition of small amounts of acid or base."},
  {"subject":"Chemistry","topic":"Physical Chemistry","difficulty":2,"question_text":"Henderson-Hasselbalch equation: pH=pKa+log([A⁻]/[HA]). At pH=pKa:","options":["[A⁻]=[HA]","[A⁻]>[HA]","[A⁻]<[HA]","No relationship"],"correct_index":0,"explanation":"When pH=pKa, log ratio=0, so [A⁻]/[HA]=1, i.e., equal concentrations."},
  # Biology Botany: Cell Biology
  {"subject":"Biology — Botany","topic":"Cell Biology","difficulty":1,"question_text":"The fluid mosaic model of cell membrane was proposed by:","options":["Singer and Nicolson","Watson and Crick","Schleiden and Schwann","Virchow"],"correct_index":0,"explanation":"Singer and Nicolson (1972) proposed the fluid mosaic model — phospholipid bilayer with embedded proteins."},
  {"subject":"Biology — Botany","topic":"Cell Biology","difficulty":1,"question_text":"ATP is synthesized in mitochondria by:","options":["Oxidative phosphorylation","Glycolysis","Photosynthesis","Fermentation"],"correct_index":0,"explanation":"Oxidative phosphorylation in the inner mitochondrial membrane produces most cellular ATP."},
  {"subject":"Biology — Botany","topic":"Cell Biology","difficulty":2,"question_text":"Ribosomes are found in:","options":["Both prokaryotes and eukaryotes","Only eukaryotes","Only prokaryotes","Only plants"],"correct_index":0,"explanation":"Ribosomes (site of protein synthesis) are universal — found in all living cells, though 70S in prokaryotes and 80S in eukaryotes."},
  {"subject":"Biology — Botany","topic":"Cell Biology","difficulty":2,"question_text":"Lysosomes are called 'suicide bags' because they:","options":["Contain hydrolytic enzymes that digest cell components","Explode during apoptosis","Kill bacteria","Destroy mitochondria only"],"correct_index":0,"explanation":"Lysosomes contain hydrolytic enzymes (acid hydrolases) that can digest all cellular macromolecules."},
  {"subject":"Biology — Botany","topic":"Cell Biology","difficulty":2,"question_text":"The Golgi apparatus is responsible for:","options":["Protein processing and secretion","DNA replication","Photosynthesis","Lipid synthesis only"],"correct_index":0,"explanation":"Golgi complex modifies, packages, and ships proteins to their destinations (secretory pathway)."},
  {"subject":"Biology — Botany","topic":"Cell Biology","difficulty":1,"question_text":"Mitosis results in:","options":["Two genetically identical diploid cells","Four haploid cells","Two haploid cells","One diploid cell"],"correct_index":0,"explanation":"Mitosis: somatic cell division producing 2 identical daughter cells with same chromosome number."},
  # Biology Botany: Plant Physiology
  {"subject":"Biology — Botany","topic":"Plant Physiology","difficulty":1,"question_text":"The site of photosynthesis in a cell is:","options":["Chloroplast","Mitochondria","Nucleus","Vacuole"],"correct_index":0,"explanation":"Chloroplasts contain chlorophyll and are the site of light reactions and Calvin cycle."},
  {"subject":"Biology — Botany","topic":"Plant Physiology","difficulty":2,"question_text":"C4 plants avoid photorespiration because:","options":["CO₂ is fixed first in mesophyll then released in bundle sheath","They fix CO₂ at night","They have no RuBisCO","They absorb only green light"],"correct_index":0,"explanation":"C4 plants (sugarcane, maize) use PEP carboxylase in mesophyll to concentrate CO₂ in bundle sheath cells where RuBisCO operates."},
  {"subject":"Biology — Botany","topic":"Plant Physiology","difficulty":2,"question_text":"Transpiration pull in xylem depends on:","options":["Cohesion-tension of water","Root pressure only","Active transport","Osmosis only"],"correct_index":0,"explanation":"Cohesion-tension theory: transpiration creates negative pressure; water cohesion pulls columns upward."},
  {"subject":"Biology — Botany","topic":"Plant Physiology","difficulty":1,"question_text":"Phytohormone promoting fruit ripening is:","options":["Ethylene","Auxin","Gibberellin","Cytokinin"],"correct_index":0,"explanation":"Ethylene (a gas) promotes fruit ripening, leaf abscission, and senescence."},
  {"subject":"Biology — Botany","topic":"Plant Physiology","difficulty":2,"question_text":"The Calvin cycle occurs in:","options":["Stroma of chloroplast","Thylakoid membrane","Matrix of mitochondria","Cytoplasm"],"correct_index":0,"explanation":"Dark reactions (Calvin/C3 cycle) fix CO₂ in the stroma using ATP and NADPH from light reactions."},
  # Biology Botany: Genetics
  {"subject":"Biology — Botany","topic":"Genetics","difficulty":1,"question_text":"DNA double helix was proposed by:","options":["Watson and Crick","Mendel","Darwin","Morgan"],"correct_index":0,"explanation":"Watson and Crick (1953) proposed the double helix model based on Franklin's X-ray data."},
  {"subject":"Biology — Botany","topic":"Genetics","difficulty":2,"question_text":"In incomplete dominance, F1 of red×white flower is:","options":["Pink","Red","White","Half red half white"],"correct_index":0,"explanation":"Neither allele is dominant; F1 shows intermediate phenotype (pink)."},
  {"subject":"Biology — Botany","topic":"Genetics","difficulty":2,"question_text":"A man with blood group AB and woman with O. Possible blood groups in children:","options":["A and B only","AB only","O only","A, B, AB, O"],"correct_index":0,"explanation":"Father AB (I^A I^B) × Mother O (ii). Children: I^A i (A) or I^B i (B). Only A and B."},
  {"subject":"Biology — Botany","topic":"Genetics","difficulty":3,"question_text":"In a testcross of Aa×aa, expected ratio of phenotypes:","options":["1:1","3:1","1:2:1","All dominant"],"correct_index":0,"explanation":"Aa×aa → 1/2 Aa (dominant) : 1/2 aa (recessive). Ratio 1:1."},
  {"subject":"Biology — Botany","topic":"Genetics","difficulty":2,"question_text":"Polyploidy is most common in:","options":["Plants","Insects","Mammals","Bacteria"],"correct_index":0,"explanation":"Polyploidy (multiple chromosome sets) is very common in flowering plants; drives speciation."},
  # Biology Botany: Ecology
  {"subject":"Biology — Botany","topic":"Ecology","difficulty":1,"question_text":"The primary producers in an ecosystem are:","options":["Green plants","Herbivores","Decomposers","Carnivores"],"correct_index":0,"explanation":"Green plants fix solar energy via photosynthesis — they are autotrophs/primary producers."},
  {"subject":"Biology — Botany","topic":"Ecology","difficulty":2,"question_text":"10% energy law in ecological pyramids means:","options":["10% of energy transfers to next trophic level","90% transfers","10% is lost as heat","10% used in growth"],"correct_index":0,"explanation":"Lindeman's 10% law: only ~10% of energy at one trophic level passes to the next."},
  {"subject":"Biology — Botany","topic":"Ecology","difficulty":1,"question_text":"Biodiversity hotspot means:","options":["Area with high species richness under threat","Very hot region","Area with many predators","Volcanic region"],"correct_index":0,"explanation":"Biodiversity hotspots: regions with >1500 endemic plant species that have lost >70% of original habitat."},
  {"subject":"Biology — Botany","topic":"Ecology","difficulty":2,"question_text":"Nitrogen fixation is carried out by:","options":["Rhizobium bacteria","Nitrifying bacteria","Denitrifying bacteria","Decomposers"],"correct_index":0,"explanation":"Rhizobium (in root nodules) and free-living bacteria (Azotobacter) fix atmospheric N₂."},
  # Biology Botany: Plant Kingdom
  {"subject":"Biology — Botany","topic":"Plant Kingdom","difficulty":1,"question_text":"Which plant group has true vascular tissue but no seeds?","options":["Pteridophytes","Bryophytes","Gymnosperms","Angiosperms"],"correct_index":0,"explanation":"Pteridophytes (ferns) have xylem and phloem but reproduce by spores, not seeds."},
  {"subject":"Biology — Botany","topic":"Plant Kingdom","difficulty":2,"question_text":"Bryophytes are called amphibians of the plant kingdom because:","options":["They need water for reproduction","They live in water and land","They have gills","They breathe like amphibians"],"correct_index":0,"explanation":"Bryophytes grow on land but require water for fertilization (flagellate sperms swim to egg)."},
  {"subject":"Biology — Botany","topic":"Plant Kingdom","difficulty":1,"question_text":"Angiosperms are different from gymnosperms in having:","options":["Enclosed seeds (fruits)","Naked seeds","No flowers","Vascular tissue"],"correct_index":0,"explanation":"Angiosperms have seeds enclosed in a fruit (ovary wall). Gymnosperms have naked seeds."},
  {"subject":"Biology — Botany","topic":"Plant Kingdom","difficulty":2,"question_text":"Alternation of generations in plants refers to:","options":["Alternating sporophyte and gametophyte","Day and night cycle","Summer and winter growth","Sexual and asexual reproduction"],"correct_index":0,"explanation":"Plant life cycles alternate between diploid sporophyte (2n) and haploid gametophyte (n) generations."},
  # Biology Zoology: Human Physiology
  {"subject":"Biology — Zoology","topic":"Human Physiology","difficulty":1,"question_text":"Normal human body temperature is:","options":["37°C (98.6°F)","36°C","38°C","35°C"],"correct_index":0,"explanation":"Normal core body temperature is ~37°C (98.6°F), maintained by thermoregulation."},
  {"subject":"Biology — Zoology","topic":"Human Physiology","difficulty":2,"question_text":"Insulin is produced by which cells of the pancreas?","options":["Beta cells of Islets of Langerhans","Alpha cells","Delta cells","Acinar cells"],"correct_index":0,"explanation":"Beta cells in Islets of Langerhans secrete insulin in response to high blood glucose."},
  {"subject":"Biology — Zoology","topic":"Human Physiology","difficulty":2,"question_text":"The functional unit of the kidney is:","options":["Nephron","Glomerulus","Bowman's capsule","Loop of Henle"],"correct_index":0,"explanation":"Nephron is the structural and functional unit of the kidney; ~1 million per kidney."},
  {"subject":"Biology — Zoology","topic":"Human Physiology","difficulty":1,"question_text":"Which enzyme in saliva begins carbohydrate digestion?","options":["Salivary amylase (ptyalin)","Lipase","Pepsin","Trypsin"],"correct_index":0,"explanation":"Salivary amylase (ptyalin) breaks down starch into maltose in the mouth."},
  {"subject":"Biology — Zoology","topic":"Human Physiology","difficulty":2,"question_text":"Neurotransmitter at neuromuscular junction is:","options":["Acetylcholine","Dopamine","Serotonin","Norepinephrine"],"correct_index":0,"explanation":"Acetylcholine (ACh) is released from motor neurons at the neuromuscular junction."},
  {"subject":"Biology — Zoology","topic":"Human Physiology","difficulty":3,"question_text":"During strenuous exercise, which metabolic pathway is used for quick ATP?","options":["Lactic acid fermentation","Aerobic respiration","Fatty acid oxidation","Gluconeogenesis"],"correct_index":0,"explanation":"In anaerobic conditions, pyruvate → lactic acid, regenerating NAD⁺ for glycolysis to continue producing ATP quickly."},
  # Biology Zoology: Reproduction
  {"subject":"Biology — Zoology","topic":"Reproduction","difficulty":1,"question_text":"Fertilization in humans occurs in:","options":["Fallopian tube","Uterus","Ovary","Cervix"],"correct_index":0,"explanation":"Fertilization (sperm meets egg) occurs in the ampulla of the fallopian (uterine) tube."},
  {"subject":"Biology — Zoology","topic":"Reproduction","difficulty":2,"question_text":"Which hormone maintains corpus luteum during early pregnancy?","options":["hCG (human Chorionic Gonadotropin)","LH","FSH","Progesterone"],"correct_index":0,"explanation":"hCG secreted by the embryo after implantation mimics LH and maintains the corpus luteum."},
  {"subject":"Biology — Zoology","topic":"Reproduction","difficulty":2,"question_text":"Meiosis ensures:","options":["Genetic variation and halving of chromosome number","Identical daughter cells","DNA replication","No genetic change"],"correct_index":0,"explanation":"Meiosis produces 4 haploid cells with genetic variation via crossing over and independent assortment."},
  {"subject":"Biology — Zoology","topic":"Reproduction","difficulty":1,"question_text":"Human gestation period is approximately:","options":["280 days","360 days","180 days","120 days"],"correct_index":0,"explanation":"Human pregnancy lasts approximately 280 days (40 weeks) from last menstrual period."},
  # Biology Zoology: Evolution
  {"subject":"Biology — Zoology","topic":"Evolution","difficulty":1,"question_text":"Theory of Natural Selection was proposed by:","options":["Darwin and Wallace","Lamarck","Mendel","De Vries"],"correct_index":0,"explanation":"Charles Darwin and Alfred Russel Wallace independently proposed natural selection (1858)."},
  {"subject":"Biology — Zoology","topic":"Evolution","difficulty":2,"question_text":"Industrial melanism in peppered moths demonstrates:","options":["Natural selection","Genetic drift","Mutation","Sexual selection"],"correct_index":0,"explanation":"During industrial revolution, dark moths survived better on soot-covered trees — classic natural selection."},
  {"subject":"Biology — Zoology","topic":"Evolution","difficulty":2,"question_text":"Hardy-Weinberg equilibrium requires:","options":["Large population, random mating, no selection","Small population","Migration","Mutation pressure"],"correct_index":0,"explanation":"H-W equilibrium: no evolution when large pop, random mating, no mutation/migration/selection/genetic drift."},
  {"subject":"Biology — Zoology","topic":"Evolution","difficulty":3,"question_text":"Analogous organs suggest:","options":["Convergent evolution","Divergent evolution","Common ancestry","Genetic drift"],"correct_index":0,"explanation":"Analogous organs have similar function but different origin (e.g., bird wing and insect wing) — convergent evolution."},
  # Biology Zoology: Biotechnology
  {"subject":"Biology — Zoology","topic":"Biotechnology","difficulty":1,"question_text":"PCR (Polymerase Chain Reaction) is used to:","options":["Amplify specific DNA sequences","Sequence proteins","Clone organisms","Produce antibodies"],"correct_index":0,"explanation":"PCR amplifies target DNA exponentially using primers and Taq polymerase through thermal cycling."},
  {"subject":"Biology — Zoology","topic":"Biotechnology","difficulty":2,"question_text":"Restriction enzymes cut DNA at specific sequences called:","options":["Palindromic sequences","Random sequences","Promoter sequences","Coding sequences"],"correct_index":0,"explanation":"Restriction endonucleases recognise and cut at specific palindromic sequences (read same 5'→3' on both strands)."},
  {"subject":"Biology — Zoology","topic":"Biotechnology","difficulty":2,"question_text":"Bt toxin in transgenic plants is derived from:","options":["Bacillus thuringiensis","Agrobacterium tumefaciens","E. coli","Streptomyces"],"correct_index":0,"explanation":"Bt toxin genes (cry genes) from Bacillus thuringiensis are inserted into crop plants for pest resistance."},
  {"subject":"Biology — Zoology","topic":"Biotechnology","difficulty":1,"question_text":"Which scientist developed the first recombinant DNA in 1972?","options":["Paul Berg","James Watson","Frederick Sanger","Kary Mullis"],"correct_index":0,"explanation":"Paul Berg (1972) created the first recombinant DNA molecule, earning the 1980 Nobel Prize."},
  {"subject":"Biology — Zoology","topic":"Biotechnology","difficulty":3,"question_text":"ELISA test detects:","options":["Antigen-antibody interactions","DNA mutations","RNA splicing","Protein folding"],"correct_index":0,"explanation":"Enzyme-Linked Immunosorbent Assay (ELISA) detects antigens/antibodies using enzyme-linked secondary antibodies."},
  # Biology Zoology: Animal Kingdom
  {"subject":"Biology — Zoology","topic":"Animal Kingdom","difficulty":1,"question_text":"Which phylum includes animals with a notochord at some stage?","options":["Chordata","Echinodermata","Arthropoda","Mollusca"],"correct_index":0,"explanation":"Phylum Chordata: all members have notochord, dorsal nerve cord, pharyngeal slits at some life stage."},
  {"subject":"Biology — Zoology","topic":"Animal Kingdom","difficulty":1,"question_text":"Earthworm belongs to phylum:","options":["Annelida","Nematoda","Platyhelminthes","Arthropoda"],"correct_index":0,"explanation":"Earthworm = Lumbricus terrestris, phylum Annelida (segmented worms)."},
  {"subject":"Biology — Zoology","topic":"Animal Kingdom","difficulty":2,"question_text":"Insects are distinguished by having:","options":["6 legs and 3 body regions","4 legs and 2 body regions","8 legs and 2 body regions","10 legs and 2 body regions"],"correct_index":0,"explanation":"Class Insecta: 3 pairs of legs (6), 3 body regions (head, thorax, abdomen)."},
  {"subject":"Biology — Zoology","topic":"Animal Kingdom","difficulty":2,"question_text":"Mammals are unique in having:","options":["Mammary glands and hair","Warm blood only","Four-chambered heart","Vertebral column"],"correct_index":0,"explanation":"Defining mammalian characters: mammary glands (milk), hair/fur, three middle ear bones."},
]

def build_bank(questions, exam_key):
    result = []
    seen = set()
    for q in questions:
        key = q["question_text"].strip().lower()[:120]
        if key in seen:
            continue
        seen.add(key)
        subj = q["subject"].replace(" ","_").replace("—","").lower()[:6]
        topic = q["topic"].replace(" ","_").replace("&","n").lower()[:6]
        q["id"] = f"{exam_key}_{subj}_{topic}_{uuid.uuid4().hex[:6]}"
        result.append(q)
    random.shuffle(result)
    return result

for exam_key, questions in [("nda", NDA), ("jee", JEE), ("neet", NEET)]:
    bank = build_bank(questions, exam_key)
    path = BANK_DIR / f"{exam_key}.json"
    path.write_text(json.dumps(bank, indent=2, ensure_ascii=False))
    from collections import Counter
    topics = Counter(q["topic"] for q in bank)
    print(f"\n{exam_key.upper()}: {len(bank)} unique questions")
    for t, c in sorted(topics.items()):
        print(f"  {t}: {c}")
