"""
Question quality guard-rail.

Call validate_question(q) before saving any MCQ to a question bank.
Returns (True, None) if the question passes, or (False, reason_string) if rejected.

Catches:
  - Template/placeholder questions generated by expand_question_banks.py-style scripts
  - Circular options that reference only the topic name
  - Too-short or missing fields
  - Trivially obvious correct answers (all options clearly wrong except one)
  - Correct index out of range
  - Duplicate options
"""

import re
from typing import Any

# ── Patterns that identify placeholder / template questions ────────────────────

_BAD_QUESTION_PATTERNS = [
    # expand_question_banks.py template
    r"which of the following is a key concept related to",
    r"which of the following best describes .{0,30} in .{0,30}\?$",
    r"which is a key concept of",
    r"which is a fundamental principle of",
    # Generic filler
    r"which of the following is true about .{0,30}\?$",
    r"which statement is correct about .{0,30}\?$",
    r"what is the importance of .{0,30} in .{0,30}\?$",
    r"which of the following relates to .{0,30}\?$",
]

_BAD_OPTION_PATTERNS = [
    # expand_question_banks.py option templates
    r"^a core principle of ",
    r"^an unrelated concept to ",
    r"^a common misconception about ",
    r"^a theory (completely )?opposite to ",
    r"^the (main|primary|key) (principle|concept|idea) of ",
    r"^something (unrelated|opposite) to ",
    # Circular single-word stuffing
    r"^(option [abcd]|answer [abcd])$",
    r"^(true|false|yes|no)$",
    # Identical filler
    r"^(none of (the )?above|all of (the )?above)$",
]

# At least one of these signals a real, specific question
_SPECIFICITY_SIGNALS = [
    r"\d",                          # any digit (numerical value)
    r"\b(who|when|where|which year|how many|calculate|find|what is the value)\b",
    r"%|₹|km|kg|m/s|hz|ohm|volt|amp|joule|watt|newton|pascal|mol|°[cf]",
    r"\b(act|article|section|amendment|treaty|formula|theorem|law|equation)\b",
    r"\b(century|bc|ad|1[0-9]{3}|20[0-9]{2})\b",   # historical dates
]


def _matches_any(text: str, patterns: list[str]) -> str | None:
    """Return first matching pattern string, or None."""
    t = text.strip().lower()
    for p in patterns:
        if re.search(p, t):
            return p
    return None


def validate_question(q: dict[str, Any]) -> tuple[bool, str | None]:
    """
    Returns (True, None) on pass.
    Returns (False, reason) on fail — caller should discard the question.
    """
    # ── 1. Required fields present ─────────────────────────────────────────────
    # Accept either question_text (diagnostic format) or question_text_en (assessment format)
    if not (q.get("question_text") or q.get("question_text_en")):
        return False, "Missing required field: 'question_text'"
    for field in ("options", "correct_index"):
        if not q.get(field) and q.get(field) != 0:
            return False, f"Missing required field: '{field}'"

    question_text: str = q.get("question_text") or q.get("question_text_en", "")
    options: list = q.get("options", [])
    correct_index = q.get("correct_index", -1)
    explanation: str = q.get("explanation") or q.get("explanation_en", "")

    # ── 2. Question text minimum length ────────────────────────────────────────
    if len(question_text.strip()) < 20:
        return False, f"Question too short ({len(question_text.strip())} chars)"

    # ── 3. Template question patterns ──────────────────────────────────────────
    bad_pat = _matches_any(question_text, _BAD_QUESTION_PATTERNS)
    if bad_pat:
        return False, f"Template question detected — matches pattern: '{bad_pat}'"

    # ── 4. Must have exactly 4 options ─────────────────────────────────────────
    if len(options) != 4:
        return False, f"Expected 4 options, got {len(options)}"

    # ── 5. Options: minimum length, not templates, not circular ───────────────
    for i, opt in enumerate(options):
        opt_str = str(opt).strip()
        if len(opt_str) < 2:
            return False, f"Option {i} is too short: '{opt_str}'"

        bad_opt = _matches_any(opt_str, _BAD_OPTION_PATTERNS)
        if bad_opt:
            return False, f"Option {i} is a placeholder/template: '{opt_str}'"

        # Circular: option just restates the topic from the question
        # e.g. question mentions "Number System", option says "Number System concept"
        topic = str(q.get("topic", "")).strip().lower()
        if topic and len(topic) > 4:
            ratio = opt_str.lower().count(topic) / max(1, len(opt_str.split()))
            if ratio > 0.5:
                return False, f"Option {i} is circular (just repeats topic name): '{opt_str}'"

    # ── 6. Duplicate options ────────────────────────────────────────────────────
    normalised = [str(o).strip().lower() for o in options]
    if len(set(normalised)) < len(normalised):
        return False, "Duplicate options detected"

    # ── 7. correct_index in range ──────────────────────────────────────────────
    if not (0 <= int(correct_index) <= 3):
        return False, f"correct_index {correct_index} is out of range 0-3"

    # ── 8. Specificity — question must contain at least one concrete signal ────
    has_signal = any(
        re.search(p, question_text.lower()) for p in _SPECIFICITY_SIGNALS
    )
    if not has_signal:
        # Softer check: question must be at least 40 chars and not end with a topic name
        if len(question_text.strip()) < 40:
            return False, (
                "Question lacks specificity (no numbers, dates, laws, or named concepts) "
                "and is too short to be a real exam question"
            )

    # ── 9. Explanation should not be circular ──────────────────────────────────
    if explanation:
        bad_expl = _matches_any(explanation, [
            r"the core principle of .{0,30} is fundamental",
            r"is fundamental to mastering .{0,30} for the exam",
        ])
        if bad_expl:
            return False, f"Circular explanation detected: '{explanation[:80]}'"

    return True, None


def filter_questions(questions: list[dict], source: str = "") -> tuple[list[dict], list[dict]]:
    """
    Split a list into (passed, rejected).
    Logs each rejection reason.
    """
    import logging
    logger = logging.getLogger(__name__)

    passed, rejected = [], []
    for q in questions:
        ok, reason = validate_question(q)
        if ok:
            passed.append(q)
        else:
            qtext = (q.get("question_text") or q.get("question_text_en", ""))[:60]
            logger.warning(
                "QBank guard-rail REJECTED%s: %s | Q: '%s...'",
                f" [{source}]" if source else "",
                reason,
                qtext,
            )
            rejected.append(q)

    if rejected:
        logger.warning(
            "QBank guard-rail: %d/%d questions rejected%s",
            len(rejected), len(questions),
            f" from {source}" if source else "",
        )
    return passed, rejected
